//
// Created by ruben on 14/06/19.
//

#ifndef MYINVINCIBLELIBRARY_SERVER_SERVERCONTROLLER_H
#define MYINVINCIBLELIBRARY_SERVER_SERVERCONTROLLER_H


class ServerController {

};


#endif //MYINVINCIBLELIBRARY_SERVER_SERVERCONTROLLER_H
